export { default as Home } from './home'
export { default as Prizes } from './prizes'
export { default as Favorites } from './favorites'
export { default as Profile } from './profile'
export { default as PropertyDetails } from './home/propertyDetails'